name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --all

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- -D warnings
